insert into aboutt (title,text) values ('Welcome','Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                     Phasellus accumsan eget odio a rhoncus. Quisque bibendum ac nulla at varius.
                     Proin et mauris tempus, cursus tellus vel, maximus odio.
                     Mauris dignissim lorem at enim finibus pharetra.
                     Suspendisse vulputate at lectus eu accumsan. Vivamus varius semper sem.
                     Etiam sodales vitae nisl vel euismod. Ut faucibus mauris pellentesque faucibus vestibulum.
                     Praesent dignissim augue non purus cursus, blandit tempor felis dictum. Aliquam condimentum,
                     leo vitae hendrerit fringilla, lacus sem mollis leo, eget consectetur orci eros quis lacus.
                     Donec quis elit at diam eleifend consequat. Sed vestibulum scelerisque eros. Proin vitae blandit erat.
                     Integer dictum bibendum velit, vehicula laoreet tellus sodales eu. Suspendisse tristique metus erat, in consequat tellus volutpat vitae.
                     Mauris eu viverra turpis.Sed at nunc mi. Sed finibus, lectus ac lobortis finibus,
                     libero purus euismod purus, et tincidunt est sem et felis. Mauris ligula dolor,
                     faucibus vel nibh non, pharetra rutrum odio. Quisque eu suscipit purus.');

insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('T-Shirt-Black-Oversize','/img/tr1.jpg',29.99,'WOMEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Sweatshirt-Black-Regular','/img/tr4.jpg',30,'MEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('T-Shirt-White-Oversize','/img/tr2.jpg',69.95,'WOMEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Jeans-Black-Slim Fit','/img/tr5.jpg',75,'MEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Sweatshirt-Navy blue-Oversize','/img/tr6.jpg',53.99,'WOMEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Sweatpants-Gray-Regular','/img/tr8.jpg',109.99,'MEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Tonny Black Shoulder Bag-Beige','/img/tr7.jpg',51.01,'ACCESSORIES','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('River Club Jacket','/img/tr10.jpg',163.9,'MEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Tonny Black Shoulder Bag - Green','/img/ac11.jpg',70,'ACCESSORIES','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Women''s Gold Color Double Cuff','/img/ac12.jpg',79.95,'ACCESSORIES','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Cool Belt - Black','/img/ac8.jpg',25,'ACCESSORIES','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Women''s Black Plain Shirt','/img/womenproduct1.jpg',29.99,'WOMEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('K&H TWENTY-ONE Logo Printed T-Shirt','/img/womenproduct2.jpg',75,'WOMEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Women''s Jacket','/img/womenproduct3.jpg',25.99,'WOMEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Straight Collar Basic Knitted T-Shirt','/img/womenproduct4.jpg',64.95,'WOMEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Piola Club Women''s Shirt','/img/womenproduct5.jpg',69.95,'WOMEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Women''s Dark Beige Crop Denim Jacket','/img/womenproduct6.jpg',69.95,'WOMEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Blue Basic Denim Jacket','/img/womenproduct7.jpg',25,'WOMEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Women Cotton Black Blouse','/img/womenproduct8.jpg',29.99,'WOMEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Women''s Black Pants Flared Trousers','/img/womenproduct9.jpg',67.99,'WOMEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Black Half Turtleneck Women''s Blouse','/img/womenproduct10.jpg',35,'WOMEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Geometry Pattern Long Sleeve Blouse','/img/womenproduct11.jpg',33.75,'WOMEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Brown Patterned Ruffle Knitted Skirt','/img/womenproduct12.jpg',89.97,'WOMEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Brown Patterned Trousers','/img/womenproduct13.jpg',110,'WOMEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Green Knit Sweater','/img/womenproduct14.jpg',120,'WOMEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Women''s Camel-Black Half Fisherman Blouse','/img/womenproduct15.jpg',78.95,'WOMEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Green Turtleneck Sweater','/img/womenproduct16.jpg',104.85,'WOMEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('White Men''s Printed Oversize T-shirt','/img/menproduct1.jpg',45.85,'MEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Men''s Gray Boxed Shirt','/img/menproduct2.jpg',33.65,'MEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Men''s Embroidered Oversize T-Shirt','/img/menproduct3.jpg',67.99,'MEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Men''s Denim Shirt Green','/img/menproduct4.jpg',67.89,'MEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Oversize Unisex Better Late Printed Tshirt','/img/menproduct5.jpg',104,'MEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Gray Italian Cut Trousers','/img/menproduct6.jpg',89.90,'MEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Men''s Lumberjack Men''s Shirt','/img/menproduct7.jpg',33.85,'MEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Men''s Italian Cut Cargo Pocket Trousers','/img/menproduct8.jpg',104.85,'MEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Men''s White Oxford Buttoned Collar Shirt','/img/menproduct9.jpg',100,'MEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Complex Oversize College Jacket','/img/menproduct10.jpg',165,'MEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Men''s Black Classic Trousers','/img/menproduct11.jpg',45,'MEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Standard Striped Knitwear Sweater','/img/menproduct12.jpg',77.45,'MEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Italian Style Men''s Single Jacket','/img/menproduct13.jpg',150.69,'MEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Men''s Brick Bosh-x Leather Jacket','/img/menproduct14.jpg',100,'MEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Men''s Gray Knitwear Sweater','/img/menproduct15.jpg',68,'MEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Green Turtleneck Sweater','/img/menproduct16.jpg',104.85,'MEN','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');

insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Shoulder Bag - White','/img/ac1.jpg',47.85,'ACCESSORIES','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Zircon stone bracelet','/img/ac2.jpg',10.85,'ACCESSORIES','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Ring set','/img/ac3.jpg',9.99,'ACCESSORIES','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Women''s Wristwatch','/img/ac4.jpg',65,'ACCESSORIES','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Men''s Ring Set','/img/ac5.jpg',9.95,'ACCESSORIES','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Rope Necklace','/img/ac6.jpg',45.80,'ACCESSORIES','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('New Season Men''s Wristwatch','/img/ac7.jpg',132,'ACCESSORIES','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Silver Knitted Bracelet','/img/ac9.jpg',12,'ACCESSORIES','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Morse Code Chain Bracelet','/img/ac10.jpg',9.50,'ACCESSORIES','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Roman Numeral Wedding Ring','/img/ac13.jpg',199.90,'ACCESSORIES','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Chain Necklace','/img/ac14.jpg',25,'ACCESSORIES','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Men''s Wrist Watch','/img/ac15.jpg',37.89,'ACCESSORIES','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');
insert into clothes (clothes_name,clothes_img,clothes_price,clothes_category,description) values ('Magnetic Clasp Braided Bracelet','/img/ac16.jpg',39.90,'ACCESSORIES','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Inventore quis, odio, nam ducimus maxime unde consequuntur tenetur iste maiores porro explicabo ipsa aliquam dolore alias! Consectetur deserunt, debitis eligendi quam esse aspernatur. Eaque itaque necessitatibus possimus aperiam. Ducimus corrupti debitis quibusdam molestiae dolorum eos, voluptatibus suscipit perferendis?');


